<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputContinue</name>
   <tag></tag>
   <elementGuidId>6b857348-96d1-4145-b27d-362063266b00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;script_content_1766410&quot;)/input[5][count(. | //input[@type = 'button' and @onclick = concat('syncLeadInfo.call(new Element(' , &quot;'&quot; , 'input' , &quot;'&quot; , ',{name:' , &quot;'&quot; , 'cl_cust-8865' , &quot;'&quot; , ',type:' , &quot;'&quot; , 'hidden' , &quot;'&quot; , ',value:' , &quot;'&quot; , 'Aetna' , &quot;'&quot; , '}),true);syncLeadInfo.call(new Element(' , &quot;'&quot; , 'input' , &quot;'&quot; , ',{name:' , &quot;'&quot; , 'cl_cust-11165' , &quot;'&quot; , ',type:' , &quot;'&quot; , 'hidden' , &quot;'&quot; , ',value:' , &quot;'&quot; , 'Aetna' , &quot;'&quot; , '}),true);syncLeadInfo.call(new Element(' , &quot;'&quot; , 'input' , &quot;'&quot; , ',{name:' , &quot;'&quot; , 'cl_cust-961' , &quot;'&quot; , ',type:' , &quot;'&quot; , 'hidden' , &quot;'&quot; , ',value:' , &quot;'&quot; , 'Aetna Medicare' , &quot;'&quot; , '}),true);syncLeadInfo.call(new Element(' , &quot;'&quot; , 'input' , &quot;'&quot; , ',{name:' , &quot;'&quot; , 'cl_cust-11263' , &quot;'&quot; , ',type:' , &quot;'&quot; , 'hidden' , &quot;'&quot; , ',value:' , &quot;'&quot; , '1' , &quot;'&quot; , '}),true);toggleDispositionFields();toggleScriptBranching();saveLeadInfo(' , &quot;'&quot; , '' , &quot;'&quot; , ',' , &quot;'&quot; , '' , &quot;'&quot; , ')') and @value = 'Continue']) = count(//input[@type = 'button' and @onclick = concat('syncLeadInfo.call(new Element(' , &quot;'&quot; , 'input' , &quot;'&quot; , ',{name:' , &quot;'&quot; , 'cl_cust-8865' , &quot;'&quot; , ',type:' , &quot;'&quot; , 'hidden' , &quot;'&quot; , ',value:' , &quot;'&quot; , 'Aetna' , &quot;'&quot; , '}),true);syncLeadInfo.call(new Element(' , &quot;'&quot; , 'input' , &quot;'&quot; , ',{name:' , &quot;'&quot; , 'cl_cust-11165' , &quot;'&quot; , ',type:' , &quot;'&quot; , 'hidden' , &quot;'&quot; , ',value:' , &quot;'&quot; , 'Aetna' , &quot;'&quot; , '}),true);syncLeadInfo.call(new Element(' , &quot;'&quot; , 'input' , &quot;'&quot; , ',{name:' , &quot;'&quot; , 'cl_cust-961' , &quot;'&quot; , ',type:' , &quot;'&quot; , 'hidden' , &quot;'&quot; , ',value:' , &quot;'&quot; , 'Aetna Medicare' , &quot;'&quot; , '}),true);syncLeadInfo.call(new Element(' , &quot;'&quot; , 'input' , &quot;'&quot; , ',{name:' , &quot;'&quot; , 'cl_cust-11263' , &quot;'&quot; , ',type:' , &quot;'&quot; , 'hidden' , &quot;'&quot; , ',value:' , &quot;'&quot; , '1' , &quot;'&quot; , '}),true);toggleDispositionFields();toggleScriptBranching();saveLeadInfo(' , &quot;'&quot; , '' , &quot;'&quot; , ',' , &quot;'&quot; , '' , &quot;'&quot; , ')') and @value = 'Continue'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>syncLeadInfo.call(new Element('input',{name:'cl_cust-8865',type:'hidden',value:'Aetna'}),true);syncLeadInfo.call(new Element('input',{name:'cl_cust-11165',type:'hidden',value:'Aetna'}),true);syncLeadInfo.call(new Element('input',{name:'cl_cust-961',type:'hidden',value:'Aetna Medicare'}),true);syncLeadInfo.call(new Element('input',{name:'cl_cust-11263',type:'hidden',value:'1'}),true);toggleDispositionFields();toggleScriptBranching();saveLeadInfo('','')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;script_content_1766410&quot;)/input[5]</value>
   </webElementProperties>
</WebElementEntity>
