<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>initiateAgentLink</name>
   <tag></tag>
   <elementGuidId>c98b7633-bea7-41c8-9800-aa58f631814a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>///li[@innertext='Initiate Agent'][count(. | //*[(text() = 'Initiate Agent' or . = 'Initiate Agent')]) = count(//*[(text() = 'Initiate Agent' or . = 'Initiate Agent')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>normal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>goTo('/cti/agents/call.html');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Initiate Agent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[@id='menu']//ul[@class='styled']/li[2]</value>
   </webElementProperties>
</WebElementEntity>
